### ISSUE TITLE
System.Net.Http.HttpRequestException occured in ping-pong process

### ISSUE THREAD

**Issue by KonH** [jweber/SlackBotNet#3]
Hi! We faced to another issue with unhandled exception in ping-pong progress, and as I see we can't handle it on our side.

**Steps to reproduce:**
- Start bot
- Disable network connection
- Wait several seconds

**Details:**
Exception is at SlackRtmDriver.cs:75:
`                        
   await this.ReconnectRtmAsync(bus, logger); <== here
`

> System.Net.Http.HttpRequestException occurred
>   HResult=0x80072EE7
>   Message=An error occurred while sending the request.
>   Source=<Cannot evaluate the exception source>
>   StackTrace:
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at System.Net.Http.HttpClient.<GetContentAsync>d__32`1.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at SlackBotNet.Drivers.SlackRtmDriver.<ConnectRtmAsync>d__8.MoveNext() in C:\projects\other\slackbotnet\src\SlackBotNet\Drivers\SlackRtmDriver.cs:line 116
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at SlackBotNet.Drivers.SlackRtmDriver.<>c__DisplayClass6_0.<<ConnectAsync>b__0>d.MoveNext() in C:\projects\other\slackbotnet\src\SlackBotNet\Drivers\SlackRtmDriver.cs:line 75
> 
> Inner Exception 1:
> WinHttpException: Can not resolve server name or address

**Comment by KonH** [comment]
In my fork I have made [hotfix](https://github.com/KonH/SlackBotNet/commit/1f276cd000238313fe5587b61f287db179b1041a), which is not acceptable for normal operation (bot can't read the messages after fail), but at least eliminates the unhandled exception. In our conditions it is suitable as a temporary solution.
For fix bot read ability In next [commit](https://github.com/KonH/SlackBotNet/commit/18cb8781af3b9e472c93d43db4422b757f62f87c) I have tried to reconnect after websocket status is not Open. I'm not sure if this is the correct solution, I didn't have enough time to adequately study the project code.

**Comment by jweber** [comment]
I put in some logic that will retry the reconnect attempts until a new socket connection can be established. My initial tests were just around the tcp connection being dropped and didn't account for a larger network disruption.

[v0.8.7](https://www.nuget.org/packages/SlackBotNet/0.8.7) has been released to NuGet with this change.  Hopefully this will resolve your issue!
