### ISSUE TITLE
Websocket connection sometimes hangs in Aborted state

### ISSUE THREAD

**Issue by KonH** [jweber/SlackBotNet#6]
Hello!
We faced with a problem, which can be reproduced in our environment when bot is running for a long time. Sometimes it denied to respond and as I see, it's related to websocket connection, which hangs in Aborted state.
I have made dirty workaround with reflection, because don't want to modify sources (now it used in several apps), I hope this commit helps to understand the problem - https://github.com/KonH/DotNetCoreBuildServer/commit/7b16dfe8d5391d75ec8c7f708dbd736b1df78805.

**Comment by jweber** [comment]
Thanks @KonH, I believe I was able to repro the issue and apply a fix for it. Your example was really helpful. I've pushed the library out to NuGet as [version 1.0.0](https://www.nuget.org/packages/SlackBotNet/1.0.0). Let me know if you continue seeing the issue.
